# Generated by Django 3.0.6 on 2020-05-28 03:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bugs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bugtracker',
            name='bug_user',
        ),
        migrations.RemoveField(
            model_name='bugtracker',
            name='comp_user',
        ),
        migrations.RemoveField(
            model_name='bugtracker',
            name='status',
        ),
        migrations.AddField(
            model_name='bugtracker',
            name='bug_reporter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bug_reporter', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bugtracker',
            name='completed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='completed_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bugtracker',
            name='ticket_status',
            field=models.CharField(choices=[('New', 'New'), ('In Progress', 'In Progress'), ('Done', 'Done'), ('Invalid', 'Invalid')], default='New', max_length=25),
        ),
        migrations.AlterField(
            model_name='bugtracker',
            name='assign_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assign_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bugtracker',
            name='description',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='bugtracker',
            name='time_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='bugtracker',
            name='title',
            field=models.TextField(max_length=100),
        ),
    ]
