# Generated by Django 3.0.6 on 2020-05-28 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0002_auto_20200528_0317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugtracker',
            name='title',
            field=models.TextField(max_length=50),
        ),
    ]
